name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/maven-reusable.yml@main
    with:
      maven_goals: 'clean install'
      java_version: '11'
